version: '3.9'

services:
  mysql_prod:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telco_db
    volumes:
      - mysql_data:/var/lib/mysql

  telco_api_prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mysql_prod
    environment:
      MYSQL_HOST: mysql_prod
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: telco_db

  telco_ui_prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - telco_api_prod

volumes:
  mysql_data:

